// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: cart.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CartService_CreateCart_FullMethodName   = "/cart.CartService/CreateCart"
	CartService_AddToCart_FullMethodName    = "/cart.CartService/AddToCart"
	CartService_GetAllCart_FullMethodName   = "/cart.CartService/GetAllCart"
	CartService_RemoveCart_FullMethodName   = "/cart.CartService/RemoveCart"
	CartService_TruncateCart_FullMethodName = "/cart.CartService/TruncateCart"
)

// CartServiceClient is the client API for CartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartServiceClient interface {
	CreateCart(ctx context.Context, in *CartCreate, opts ...grpc.CallOption) (*CartResponse, error)
	AddToCart(ctx context.Context, in *AddToCartRequst, opts ...grpc.CallOption) (*CartResponse, error)
	GetAllCart(ctx context.Context, in *CartCreate, opts ...grpc.CallOption) (CartService_GetAllCartClient, error)
	RemoveCart(ctx context.Context, in *RemoveCartRequest, opts ...grpc.CallOption) (*CartResponse, error)
	TruncateCart(ctx context.Context, in *CartCreate, opts ...grpc.CallOption) (*NoArgu, error)
}

type cartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCartServiceClient(cc grpc.ClientConnInterface) CartServiceClient {
	return &cartServiceClient{cc}
}

func (c *cartServiceClient) CreateCart(ctx context.Context, in *CartCreate, opts ...grpc.CallOption) (*CartResponse, error) {
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, CartService_CreateCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) AddToCart(ctx context.Context, in *AddToCartRequst, opts ...grpc.CallOption) (*CartResponse, error) {
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, CartService_AddToCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) GetAllCart(ctx context.Context, in *CartCreate, opts ...grpc.CallOption) (CartService_GetAllCartClient, error) {
	stream, err := c.cc.NewStream(ctx, &CartService_ServiceDesc.Streams[0], CartService_GetAllCart_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &cartServiceGetAllCartClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CartService_GetAllCartClient interface {
	Recv() (*GetAllCartResponse, error)
	grpc.ClientStream
}

type cartServiceGetAllCartClient struct {
	grpc.ClientStream
}

func (x *cartServiceGetAllCartClient) Recv() (*GetAllCartResponse, error) {
	m := new(GetAllCartResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cartServiceClient) RemoveCart(ctx context.Context, in *RemoveCartRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, CartService_RemoveCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) TruncateCart(ctx context.Context, in *CartCreate, opts ...grpc.CallOption) (*NoArgu, error) {
	out := new(NoArgu)
	err := c.cc.Invoke(ctx, CartService_TruncateCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServiceServer is the server API for CartService service.
// All implementations must embed UnimplementedCartServiceServer
// for forward compatibility
type CartServiceServer interface {
	CreateCart(context.Context, *CartCreate) (*CartResponse, error)
	AddToCart(context.Context, *AddToCartRequst) (*CartResponse, error)
	GetAllCart(*CartCreate, CartService_GetAllCartServer) error
	RemoveCart(context.Context, *RemoveCartRequest) (*CartResponse, error)
	TruncateCart(context.Context, *CartCreate) (*NoArgu, error)
	mustEmbedUnimplementedCartServiceServer()
}

// UnimplementedCartServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCartServiceServer struct {
}

func (UnimplementedCartServiceServer) CreateCart(context.Context, *CartCreate) (*CartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCart not implemented")
}
func (UnimplementedCartServiceServer) AddToCart(context.Context, *AddToCartRequst) (*CartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (UnimplementedCartServiceServer) GetAllCart(*CartCreate, CartService_GetAllCartServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllCart not implemented")
}
func (UnimplementedCartServiceServer) RemoveCart(context.Context, *RemoveCartRequest) (*CartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCart not implemented")
}
func (UnimplementedCartServiceServer) TruncateCart(context.Context, *CartCreate) (*NoArgu, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TruncateCart not implemented")
}
func (UnimplementedCartServiceServer) mustEmbedUnimplementedCartServiceServer() {}

// UnsafeCartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartServiceServer will
// result in compilation errors.
type UnsafeCartServiceServer interface {
	mustEmbedUnimplementedCartServiceServer()
}

func RegisterCartServiceServer(s grpc.ServiceRegistrar, srv CartServiceServer) {
	s.RegisterService(&CartService_ServiceDesc, srv)
}

func _CartService_CreateCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).CreateCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_CreateCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).CreateCart(ctx, req.(*CartCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToCartRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_AddToCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).AddToCart(ctx, req.(*AddToCartRequst))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_GetAllCart_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CartCreate)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CartServiceServer).GetAllCart(m, &cartServiceGetAllCartServer{stream})
}

type CartService_GetAllCartServer interface {
	Send(*GetAllCartResponse) error
	grpc.ServerStream
}

type cartServiceGetAllCartServer struct {
	grpc.ServerStream
}

func (x *cartServiceGetAllCartServer) Send(m *GetAllCartResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CartService_RemoveCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).RemoveCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_RemoveCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).RemoveCart(ctx, req.(*RemoveCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_TruncateCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).TruncateCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_TruncateCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).TruncateCart(ctx, req.(*CartCreate))
	}
	return interceptor(ctx, in, info, handler)
}

// CartService_ServiceDesc is the grpc.ServiceDesc for CartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cart.CartService",
	HandlerType: (*CartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCart",
			Handler:    _CartService_CreateCart_Handler,
		},
		{
			MethodName: "AddToCart",
			Handler:    _CartService_AddToCart_Handler,
		},
		{
			MethodName: "RemoveCart",
			Handler:    _CartService_RemoveCart_Handler,
		},
		{
			MethodName: "TruncateCart",
			Handler:    _CartService_TruncateCart_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllCart",
			Handler:       _CartService_GetAllCart_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cart.proto",
}
